### ISSUE TITLE
Jest: Cannot find module '@web3icons/core' from '../node_modules/@web3icons/react/dist/index.js'

### ISSUE THREAD

**Issue by jspradlin1-chwy** [0xa3k5/web3icons#31]
WHen I attempt to run a test on a component that has the web3 icons deeply nested in a child component, I get the following:

```
Test suite failed to run

    Cannot find module '@web3icons/core' from '../node_modules/@web3icons/react/dist/index.js'

    Require stack:
      /Users/spradlin/IntellijProjects/platform/clients/user/node_modules/@web3icons/react/dist/index.js
      /Users/spradlin/IntellijProjects/platform/clients/user/src/components/UI-kit/TokenIcon/index.jsx
      /Users/spradlin/IntellijProjects/platform/clients/user/src/components/layout/Header/wallet-new.tsx
      /Users/spradlin/IntellijProjects/platform/clients/user/src/components/layout/Header/user-nav-header.tsx
      components/layout/Header/user-nav-header.test.tsx

      1 | import React from 'react';
    > 2 | import {
        | ^
      3 |   TokenETH,
      4 |   TokenBTC,
      5 |   TokenUSDT,

      at Resolver._throwModNotFoundError (../node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.require (../node_modules/@web3icons/react/dist/index.js:184190:19)
      at Object.require (../src/components/UI-kit/TokenIcon/index.jsx:2:1)
      at Object.<anonymous> (../src/components/layout/Header/wallet-new.tsx:23:1)
      at Object.<anonymous> (../src/components/layout/Header/user-nav-header.tsx:12:1)
      at Object.<anonymous> (components/layout/Header/user-nav-header.test.tsx:1:1)

```

**Comment by jspradlin1-chwy** [comment]
To resolve the issue, i had to first add `@web3icons/core` to the project (whoever added `@web3icons/react` missed that it requires `core` as well).  THEN, i had to add a setting to jest's `moduleNameMapper` in my `jest.config.js`:

```js
  moduleNameMapper: {
    '^@src/(.*)$': '<rootDir>/../src/$1',
    '^@test/(.*)$': '<rootDir>/../test/$1',
    '\\.svg$': '<rootDir>/__mocks__/svg.js',
    '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',
    '\\.(css|sass|scss)$': '<rootDir>/__mocks__/styleMock.js',
    '@web3icons/core': '<rootDir>/../node_modules/@web3icons/core/dist/esm/index.js',
  },
```

**Comment by 0xa3k5** [comment]
thank you for reporting! The react package should not really depend on the core, I have a working branch to separate that dependency which will make it a bit lighter.
